export const meta = {
  title: "36. Putting It All Together",
  subtitle: "Calculating the final loss in three easy steps.",
};

export default function Section36() {
  return (
    <div className="space-y-4 animate-fade-in">
      <p className="text-gray-700">
        At the end of the entire network, your real pipeline data (X) has been warped into Y_final (which we call Z_final). PyTorch evaluates everything in three lines of code.
      </p>

      <div className="flex flex-col gap-4 mt-4">
         {/* Step 1 */}
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex items-start gap-4">
            <div className="bg-indigo-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shrink-0 shadow">1</div>
            <div className="w-full">
               <h4 className="font-bold text-indigo-800 mb-1">The Blueprint Score</h4>
               <code className="bg-indigo-50 text-indigo-900 px-3 py-1.5 rounded text-sm font-mono border border-indigo-100 block w-full mb-2">score = bell_curve.log_prob(Z_final)</code>
               <p className="text-xs text-gray-500 bg-slate-50 p-2 rounded border border-slate-100">
                  <strong>Notice:</strong> <code>t</code> is implicitly graded here! We don't evaluate <code>t</code> directly, but if the network chose a bad <code>t</code>, Z_final will land far away from the center of the bell curve, and this score will be terrible.
               </p>
            </div>
         </div>

         {/* Step 2 */}
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex items-start gap-4">
            <div className="bg-teal-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shrink-0 shadow">2</div>
            <div className="w-full">
               <h4 className="font-bold text-teal-800 mb-1">The Volume Penalty</h4>
               <code className="bg-teal-50 text-teal-900 px-3 py-1.5 rounded text-sm font-mono border border-teal-100 block w-full mb-2">penalty = sum(s)</code>
               <p className="text-xs text-gray-500 bg-slate-50 p-2 rounded border border-slate-100">
                  PyTorch grabs all the <code>s</code> vectors generated by your Neural Networks across every layer and simply adds them up.
               </p>
            </div>
         </div>

         {/* Step 3 */}
         <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex items-start gap-4">
            <div className="bg-rose-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shrink-0 shadow">3</div>
            <div className="w-full">
               <h4 className="font-bold text-rose-800 mb-1">Total Loss</h4>
               <code className="bg-rose-50 text-rose-900 px-3 py-1.5 rounded text-sm font-mono border border-rose-100 block w-full mb-2">loss = -1 * (score + penalty)</code>
               <p className="text-xs text-gray-500 bg-slate-50 p-2 rounded border border-slate-100">
                  We flip it negative because optimizers minimize to zero. <code>loss.backward()</code> handles the rest, tracing the math backward to update the neural network weights!
               </p>
            </div>
         </div>
      </div>
    </div>
  );
}
